# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2020 Lynn Kirby

name: Build

on:
  # Run on pushes to all branches but ignore tags.
  push:
    branches: ['**']
    tags-ignore: ['**']

jobs:
  clang-format:
    name: Lint with clang-format
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Lint with clang-format
      uses: DoozyX/clang-format-lint-action@v0.5

  reuse:
    name: Lint with REUSE
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install Python dependencies
      run: pip install reuse
    - name: Lint with REUSE
      run: reuse lint

  build:
    name: Build (${{ matrix.platform.image }})
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        platform:
        - image: ubuntu-18.04
          generator: '-G "Unix Makefiles"'
          generator_command: make
        - image: windows-2019
          generator: -GNinja
          generator_command: ninja
          # We already have Ninja installed but it's in an inconvenient place
          # and not in the PATH.
          add_path: 'C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja'
    runs-on: ${{ matrix.platform.image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Update PATH
      if: matrix.platform.add_path != null
      run: echo '##[add-path]${{ matrix.platform.add_path }}'
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake ${{ matrix.platform.generator }} ..
    - name: Build
      working-directory: build
      run: ${{ matrix.platform.generator_command }}
    - name: Test
      working-directory: build
      run: ctest --output-on-failure -V -R alltests
