/*
 * SPDX-License-Identifier: GPL-3.0-or-later AND LicenseRef-testu01
 * Copyright (c) 2002 Pierre L'Ecuyer, DIRO, Université de Montréal
 * Code derived from TestU01: http://simul.iro.umontreal.ca/testu01/tu01.html
 */

#ifndef TESTU01_H
#define TESTU01_H

#include "TestU01/bbattery.h"
#include "TestU01/fcho.h"
#include "TestU01/fcong.h"
#include "TestU01/ffam.h"
#include "TestU01/ffsr.h"
#include "TestU01/fknuth.h"
#include "TestU01/fmarsa.h"
#include "TestU01/fmultin.h"
#include "TestU01/fnpair.h"
#include "TestU01/fres.h"
#include "TestU01/fspectral.h"
#include "TestU01/fstring.h"
#include "TestU01/ftab.h"
#include "TestU01/fvaria.h"
#include "TestU01/fwalk.h"
#include "TestU01/rijndael-alg-fst.h"
#include "TestU01/scatter.h"
#include "TestU01/scomp.h"
#include "TestU01/sentrop.h"
#include "TestU01/sknuth.h"
#include "TestU01/smarsa.h"
#include "TestU01/smultin.h"
#include "TestU01/snpair.h"
#include "TestU01/sres.h"
#include "TestU01/sspacings.h"
#include "TestU01/sspectral.h"
#include "TestU01/sstring.h"
#include "TestU01/svaria.h"
#include "TestU01/swalk.h"
#include "TestU01/swrite.h"
#include "TestU01/tu01_sha1.h"
#include "TestU01/uautomata.h"
#include "TestU01/ubrent.h"
#include "TestU01/ucarry.h"
#include "TestU01/ucrypto.h"
#include "TestU01/ucubic.h"
#include "TestU01/udeng.h"
#include "TestU01/ufile.h"
#include "TestU01/ugfsr.h"
#include "TestU01/ugranger.h"
#include "TestU01/uinv.h"
#include "TestU01/uknuth.h"
#include "TestU01/ulcg.h"
#include "TestU01/ulec.h"
#include "TestU01/umarsa.h"
#include "TestU01/umrg.h"
#include "TestU01/unif01.h"
#include "TestU01/unumrec.h"
#include "TestU01/uquad.h"
#include "TestU01/usoft.h"
#include "TestU01/utaus.h"
#include "TestU01/utezuka.h"
#include "TestU01/utouzin.h"
#include "TestU01/uvaria.h"
#include "TestU01/uweyl.h"
#include "TestU01/uwu.h"
#include "TestU01/uxorshift.h"

#endif
